#________________________________ QUESTIONS ________________________________
# GET ALL QUESTIONS
GET http://localhost:5000/api/questions HTTP/1.1

###
# GET QUESTION
GET http://localhost:5000/api/questions/6299de9909660ae8bcb6e938 HTTP/1.1

###
# GET QUESTION BY LP
GET http://localhost:5000/api/questions/lp/1 HTTP/1.1

###
# CREATE QUESTION
POST http://localhost:5000/api/questions HTTP/1.1
Content-Type: application/json

{
    "lp": 1,
    "question": "Czy artykuł ma krzykliwy tytuł i bulwersujący lead, obiecujący sensację, której nie ma?",
    "answer": 1
}

###
# DELETE QUESTION
DELETE http://localhost:5000/api/questions/629b403b6ce2f93969611e44 HTTP/1.1

#________________________________ CATEGORIES ________________________________
###
# GET ALL CATEGORIES
GET http://localhost:5000/api/categories HTTP/1.1

###
# GET CATEGORY
GET http://localhost:5000/api/categories/629b40bb6ce2f93969611e49 HTTP/1.1

###
# CREATE CATEGORY
POST http://localhost:5000/api/categories HTTP/1.1
Content-Type: application/json

{
    "name": "kultura",
    "list": [1, 2, 3]
}

###
# DELETE CATEGORY
DELETE http://localhost:5000/api/categories/629bd32dc804f7f14b7db957 HTTP/1.1

#________________________________ TAGS ________________________________
###
# GET ALL TAGS
GET http://localhost:5000/api/tags HTTP/1.1

###
# CREATE TAG
POST http://localhost:5000/api/tags HTTP/1.1
Content-Type: application/json

{
    "name": "kultura"
}

###
# DELETE TAG
DELETE http://localhost:5000/api/tags/629b6493a47a1f222017cb3d HTTP/1.1

#________________________________ ARTICLES ________________________________
###
# GET ALL ARTICLES
GET http://localhost:5000/api/articles HTTP/1.1

###
# CREATE ARTICLE
POST http://localhost:5000/api/articles HTTP/1.1
Content-Type: application/json

{
    "url": "http://test1.com"
}

###
# DELETE ARTICLE
DELETE http://localhost:5000/api/articles/629b6eabda93832480888cd5 HTTP/1.1

#________________________________ SITES ________________________________
###
# GET ALL SITES
GET http://localhost:5000/api/sites HTTP/1.1

###
# CREATE SITE
POST http://localhost:5000/api/sites HTTP/1.1
Content-Type: application/json

{
    "url": "http://test1.com"
}

###
# DELETE SITE
DELETE http://localhost:5000/api/sites/629b7faa16a29d3b4bdbfd40 HTTP/1.1

#________________________________ USER ________________________________
###
# GET ALL USERS
GET http://localhost:5000/api/users HTTP/1.1

###
# CREATE USER
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

# https://pl.wikipedia.org/wiki/Paraponera_clavata
# https://czeladz.naszemiasto.pl/nasze-slodziaki-swietuja-czyli-dzien-kota-2021-zobacz-memy/ar/c11-8142405

{
    "email": "margiebed+12@gmail.com",
    "url": "https://pl.wikipedia.org/wiki/Paraponera_clavata",
    "category": "629ba7b9f0f7357914b9f628",
    "result": 20
}

###
# UPDATE USER
PUT http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "email": "margiebed+12@gmail.com",
    "url": "https://pl.wikipedia.org/wiki/Paraponera_clavata",
    "category": "629ba7b9f0f7357914b9f6zx",
    "result": 12
}

###
# DELETE USER
DELETE http://localhost:5000/api/users/629b89b298ed1592d5463ce5 HTTP/1.1

#________________________________ SCORES ________________________________
###
# GET ARTICLE SCORES
GET http://localhost:5000/api/scores/629c0279b0ed0506f68237dc HTTP/1.1
